services:
  app:
    build: .
    depends_on:
      - pg
    
  pg:
    image: postgres:16.2-alpine3.19
    volumes:
      - "./db/init.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      POSTGRES_PASSWORD: "secret"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "WIKIPEDIA_ARTICLES"